### ISSUE TITLE
Runtime problem after the build succeeds

### ISSUE THREAD

**Issue by cheickmec** [shiptwo/meteor-buildpack-horse#4]
- Failure to build
 - Runtime problem after the build succeeds

##### Summary
I followed the instructions for how to deploy reactioncommerce on heroku but after the app builds, I get the error below when visiting the app's URL. Did you face a similar issue after using this version of the buildpack? As a background to my issue, I used yoru version of the buildpack after experiencing the issue you had with the `Retrying download in 5 secs`.

##### Logs

```
2018-10-24T04:21:17.522310+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/bin/boot_proxy.js .meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2018-10-24T04:21:20.741678+00:00 heroku[web.1]: State changed from starting to crashed
2018-10-24T04:21:20.651870+00:00 app[web.1]: module.js:549
2018-10-24T04:21:20.651914+00:00 app[web.1]:     throw err;
2018-10-24T04:21:20.651916+00:00 app[web.1]:     ^
2018-10-24T04:21:20.651917+00:00 app[web.1]: 
2018-10-24T04:21:20.651926+00:00 app[web.1]: Error: Cannot find module '/app/.meteor/heroku_build/bin/boot_proxy.js'
2018-10-24T04:21:20.651932+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:547:15)
2018-10-24T04:21:20.651938+00:00 app[web.1]:     at Function.Module._load (module.js:474:25)
2018-10-24T04:21:20.651940+00:00 app[web.1]:     at Function.Module.runMain (module.js:693:10)
2018-10-24T04:21:20.651941+00:00 app[web.1]:     at startup (bootstrap_node.js:191:16)
2018-10-24T04:21:20.651947+00:00 app[web.1]:     at bootstrap_node.js:612:3
2018-10-24T04:21:20.728526+00:00 heroku[web.1]: Process exited with status 1
```

##### Deployment target

Heroku

**Comment by shiptwo** [comment]
@cheickmec this looks to be some issue with Procfile. Below is what I had in my Procfile:

```
web: .meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js
```

Can you show what you have in your Procfile?

Really sorry could not help you at the time you posted, logging in here after a long time :)
